### ISSUE TITLE
2.12.x series artifact

### ISSUE THREAD

**Issue by danslapman** [scala/scala-continuations#14]
@adriaanm I just updated scala-continuations to build against scala 2.12.0-M5, it works fine in my cases. What I have to do exactly to make apropriate artifact be published?

**Comment by SethTisue** [comment]
publishing of artifacts is tag-driven. you push a version tag and Travis runs `admin/build.sh` which (if the tag matches its regex) takes it from there, powered by https://github.com/scala/sbt-scala-modules

are you ready to publish version 1.0.3? if so, go ahead.

if you want to republish a previously published version, just for a new Scala milestone, we'd need to do some work to support that; see https://github.com/scala/sbt-scala-modules/issues/12

in this particular case, since the publishing stuff has all changed since 1.0.2 and it'll be the first time we're trying the new stuff in this particular repo, I guess I'd suggest going ahead and publishing 1.0.3 and if there aren't supposed to be any user-visible changes since 1.0.2, say so in the release notes.

**Comment by danslapman** [comment]
@SethTisue I see 2.12.0-RC1 coming soon, so I decided to publish 1.0.3 after Scala release candidate is out.

**Comment by danslapman** [comment]
Also, it is reasonable to adjust build script like here https://github.com/scala/scala-parser-combinators/pull/87/commits/cdfba62ae6ea58ceb255a1f836815fa5c9efa800

**Comment by SethTisue** [comment]
yes, I think so

**Comment by danslapman** [comment]
@SethTisue done. I see 2.12.0-RC2 coming (month and a half passed, eh), seems reasonable to publish a new RC of scala-continuations with it

**Comment by SethTisue** [comment]
sounds good

**Comment by danslapman** [comment]
- add to https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md when done

**Comment by danslapman** [comment]
@SethTisue just pushed 1.0.3-RC3 tag, artifacts seems to be staged.

**Comment by danslapman** [comment]
I see messages like this in build log
`[info] 	published scala-continuations-library_2.12.0-RC2 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/plugins/scala-continuations-library_2.12.0-RC2/1.0.3-RC3/scala-continuations-library_2.12.0-RC2-1.0.3-RC3.jar.asc`
@SethTisue have You got credentials to release artifacts from the staging?

**Comment by adriaanm** [comment]
I see 2.11.8 and 2.12.0-RC2 artifacts at https://oss.sonatype.org/content/repositories/orgscala-lang-1350/org/scala-lang/plugins/ and https://oss.sonatype.org/content/repositories/orgscala-lang-1349/org/scala-lang/plugins/. Happy to promote both to maven central!

**Comment by adriaanm** [comment]
I have unleashed them! Onwards to Maven Central!

**Comment by danslapman** [comment]
@adriaanm thanks!
