### ISSUE TITLE
archive this repo?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-continuations#73]
it seems highly unlikely at this point that a new volunteer maintainer is going to step up (see #37, #49, #50)

I suggest we simply archive this repo. any objections? @scala/committers 

at archiving time, we should put something in the repo README. perhaps simply:

> This repository has been archived, for lack of volunteer maintainers. Past releases remain available on Maven Central.

**Comment by martijnhoekstra** [comment]
Maybe also a note whom to contact in the event a volunteer does at some point step up?

**Comment by som-snytt** [comment]
> for lack of volunteer maintainers.

Maybe add:

> This is why we can't have nice things.

A "note whom to contact" should not be necessary, as there are instructions in the readme. When a repo is archived, it is automatically included on the next NASA deep space probe, so that if an alien volunteer comes across it and wants to contribute, it will send a ping back across interstellar space. Travelling at the speed of light, the message will arrive in about the same time it takes to get a PR merged.

**Comment by NthPortal** [comment]
> A "note whom to contact" should not be necessary, as there are instructions in the readme

except that you can't open an issue once it's archived

**Comment by SethTisue** [comment]
I updated the readme here: https://github.com/scala/scala-continuations/commit/17008dcb93aa4a82de7ee71d842d138d7b6706ce

I didn't add contact information as such information might go out of date. If someone is seriously interested in reviving the repo, they can post to https://contributors.scala-lang.org or get in touch with any of us in a myriad of ways.
